release:
  mode: replace

before:
  hooks:
    - go mod tidy
builds:
  -
    id: ripley
    main: ./cmd/ripley
    binary: ripley
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
  -
    id: ripleysort
    main: ./cmd/ripleysort
    binary: ripleysort
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: ripley
    tap:
      owner: loveholidays
      name: homebrew-tap
    commit_author:
      name: loveholidays
      email: oss@loveholidays.com
    folder: Formula
    homepage: "https://github.com/loveholidays/ripley"
    description: "Replays HTTP traffic at multiples of the original rate"
    install: |
      bin.install "ripley"
    license: "GPL-3.0"
  -
    name: ripleysort
    tap:
      owner: loveholidays
      name: homebrew-tap
    commit_author:
      name: loveholidays
      email: oss@loveholidays.com
    folder: Formula
    homepage: "https://github.com/loveholidays/ripley#ripleysort"
    description: "Stream sorts JSONL by a top level 'timestamp' field"
    install: |
      bin.install "ripleysort"
    license: "GPL-3.0"
dockers:
  - image_templates: ["loveholidays/{{ .ProjectName }}:{{ .Version }}-amd64"]
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/loveholidays/ripley
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=GPL-3.0
  - image_templates: [ "loveholidays/{{ .ProjectName }}:latest" ]
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/loveholidays/ripley
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=GPL-3.0
