name: Publish System Catalog

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"
      - "develop"
    paths:
      - ".system-catalog/**/*.yaml"
      - ".system-catalog/**/*.yml"

permissions:
  contents: read
  id-token: write
jobs:
  run-publish:
    uses: loveholidays/github-actions/.github/workflows/system-catalog-publish.yaml@main
    with:
      project_id: lh-cloud-infra-ops-production
      pubsub_topic: system_catalog
      runner: ops-production-arm64-1cpu-2gb
    secrets: inherit # This passes GITHUB_TOKEN to the reusable workflow
